/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'toys' : IDL.Null,
  'homeKitchen' : IDL.Null,
  'beauty' : IDL.Null,
  'sports' : IDL.Null,
  'fashion' : IDL.Null,
  'electronics' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Bool,
  'originalPrice' : IDL.Float64,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
  'reviewCount' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([Product], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCart' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(CartItem, IDL.Opt(Product)))],
      ['query'],
    ),
  'getCartTotal' : IDL.Func([], [IDL.Float64], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'seedProducts' : IDL.Func([], [], []),
  'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'toys' : IDL.Null,
    'homeKitchen' : IDL.Null,
    'beauty' : IDL.Null,
    'sports' : IDL.Null,
    'fashion' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Bool,
    'originalPrice' : IDL.Float64,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
    'reviewCount' : IDL.Nat,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  
  return IDL.Service({
    'addProduct' : IDL.Func([Product], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCart' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(CartItem, IDL.Opt(Product)))],
        ['query'],
      ),
    'getCartTotal' : IDL.Func([], [IDL.Float64], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'seedProducts' : IDL.Func([], [], []),
    'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };